# Generated by Django 3.0.7 on 2020-06-12 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by', models.CharField(max_length=100)),
                ('question_text', models.CharField(max_length=140)),
                ('channel_id', models.CharField(max_length=100)),
            ],
        ),
    ]
