# Generated by Django 3.0.7 on 2020-06-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='message_ts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(blank=True, choices=[('U', 'Urgent'), ('N', 'Normal'), ('W', 'Whenever')], max_length=2, null=True),
        ),
    ]
