# Generated by Django 3.0.7 on 2020-06-12 16:32

from django.db import migrations

from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200612_0614'),
    ]

    operations = [
        HStoreExtension(),
    ]
