# Generated by Django 3.0.7 on 2020-06-16 01:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='responses',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
