version: '3'

services:
    redis:
      image: redis:latest
      ports:
        - 6379:6379
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      build: .
      command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      container_name: yes_no
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
    celery:
      build: .
      command: celery -A yes_no worker --beat --scheduler django --loglevel=info
      volumes:
        - .:/code
      depends_on:
        - db
        - redis
    celery-beat:
      build: .
      command: celery -A yes_no beat -l info --pidfile=/tmp/celeryd.pid
      volumes:
        - .:/code
      depends_on:
        - db
        - redis