# Generated by Django 3.0.7 on 2020-06-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bot_access_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='bot_slack_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
